// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    evolgo_staking
    (
        init => init
        upgrade => upgrade
        stake => stake
        unstake => unstake
        claimRewards => claim_rewards
        fundRewards => fund_rewards
        getStakingToken => staking_token
        getNextPositionId => next_position_id
        getPosition => positions
        getUserPositionIds => user_position_ids
        getTotalStakedInPool => total_staked_in_pool
        getSyndicateStaked => syndicate_staked
        isSyndicateEligible => is_syndicate_eligible
        getPendingRewards => get_pending_rewards_view
        getUserPositions => get_user_positions
        getPoolApyBps => get_pool_apy_bps
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
